version: '3.9'

services:
  db-init:
    image: postgres:15
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /var/lib/postgresql/data

  db:
    image: postgres:15
    user: 2000:2000
    shm_size: 256m
    restart: always
    container_name: 'db'
    command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
    environment:
      POSTGRES_DB: 'railway'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'lEYrTfwRcOAUGRTVMyaeQIjiSuRLpgew'
      POSTGRES_HOST: 'roundhouse.proxy.rlwy.net'
      POSTGRES_PORT: 52720
    ports:
      - target: 5432
        published: 7432
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d railway -h roundhouse.proxy.rlwy.net -p 52720"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
